Prepare release 0.10.0.
openeuropa/oe_translation pull request #121
Opened 2020-12-08 13:23 UTC by imanoleguskiza

## EWPP
### Description

Update changelog for release 0.10.0.

### Change log

- Added:
- Changed: Update changelog for release 0.10.0.
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2020-12-08 13:23 UTC, upchuk approved these changes

2020-12-08 13:50 UTC, upchuk requested changes
Let's wait on this release.

2021-01-25 09:24 UTC, 22Alexandra approved these changes

2021-01-25 09:24 UTC, upchuk approved these changes

2021-01-25 09:24 UTC, merged