EWPP-706: Fixing type hint that assumes local translations work with Node only.
openeuropa/oe_translation pull request #124
Opened 2021-01-26 11:39 UTC by upchuk

]

2021-01-26 17:22 UTC, brummbar requested changes

2021-01-26 17:22 UTC, brummbar commented on src/Plugin/tmgmt/Translator/PermissionTranslator.php
>     * Creates the source data ready to be translated for a node.
Node to content entity.

2021-01-26 17:22 UTC, brummbar commented on src/Plugin/tmgmt/Translator/PermissionTranslator.php
>     *   The node.
The content entity.

2021-01-27 12:50 UTC, brummbar approved these changes

2021-01-29 10:21 UTC, imanoleguskiza approved these changes

2021-02-02 08:03 UTC, merged