EWPP-769: Allowing a retry on accepting a translation.
openeuropa/oe_translation pull request #128
Opened 2021-02-11 10:44 UTC by upchuk

2021-02-15 11:39 UTC, imanoleguskiza requested changes

2021-02-15 11:39 UTC, imanoleguskiza commented on modules/oe_translation_poetry/oe_translation_poetry.module
> +    // or if there is no translation on the target entity from this job item.
This is a bit misleading I think, what is happening is more like "Forbid access to job item updates if they are not waiting to be accepted or if the source entity for this item is no longer available.".

2021-02-15 14:08 UTC, 22Alexandra approved these changes

2021-02-22 12:37 UTC, imanoleguskiza approved these changes

2021-02-22 12:40 UTC, merged