EWPP-3146: Fixing leftover todos from removing TMGMT.
openeuropa/oe_translation pull request #214
Opened 2023-03-13 13:50 UTC by upchuk

2023-03-13 14:17 UTC, upchuk commented on src/TranslationSourceFieldProcessor/DefaultFieldProcessor.php
> -   * @todo add logic from https://www.drupal.org/project/tmgmt/issues/2942236
Turns out this was already there.

2023-03-13 14:18 UTC, upchuk commented on tests/src/Kernel/LinkFieldProcessorTest.php
> -<?php
This test was only needed when we were altering tmgmt to use the default field processor.

2023-03-13 14:29 UTC, 22Alexandra commented on tests/src/Kernel/TranslationSourceTest.php
> +    // Inform the test even subscriber to add some extra field to the
```suggestion
    // Inform the test event subscriber to add some extra field to the
```

2023-03-13 14:32 UTC, 22Alexandra submitted a review, later dismissed

2023-03-15 15:13 UTC, hernani commented
https://github.com/openeuropa/oe_translation/blob/EWPP-3146-3/oe_translation.install#L35  tmgmt still used

2023-03-15 15:28 UTC, hernani commented
https://github.com/openeuropa/oe_translation/blob/EWPP-3146-3/modules/oe_translation_corporate_workflow/oe_translation_corporate_workflow.module#L116

https://github.com/openeuropa/oe_translation/blob/EWPP-3146-3/modules/oe_translation_corporate_workflow/oe_translation_corporate_workflow.module#L287

https://github.com/openeuropa/oe_translation/blob/EWPP-3146-3/modules/oe_translation_corporate_workflow/tests/src/Kernel/CorporateWorkflowTranslationTest.php#L109

https://github.com/openeuropa/oe_translation/blob/EWPP-3146-3/modules/oe_translation_local/tests/src/Functional/LocalTranslationsTest.php#L55

2023-03-16 15:00 UTC, hernani commented
Remote translation module needs options module as dependency

2023-03-16 15:05 UTC, hernani requested changes

2023-03-17 12:11 UTC, 22Alexandra approved these changes

2023-03-17 12:11 UTC, merged