EWPP-3127: Clear field values which are not in the translation data.
openeuropa/oe_translation pull request #219
Opened 2023-03-16 12:57 UTC by upchuk

2023-03-16 15:39 UTC, 22Alexandra requested changes

2023-03-16 15:39 UTC, 22Alexandra commented on src/TranslationFormTrait.php
> +            'warning' => [$this->t('Source value for the field <em>@name</em> was removed. Synchronising this translation will remove the value from the translation as well.', ['@name' => $data[$key]
When removing the value of a paragraph field `$data[$key]['#parent_label'][0]` contains the entity reference revisions field label.

When multiple fields had their values removed, the warning mentions only the last field.

2023-03-20 10:24 UTC, upchuk commented
@22Alexandra 

> When removing the value of a paragraph field $data[$key]['#parent_label'][0] contains the entity reference revisions field label.

Fixed

> When multiple fields had their values removed, the warning mentions only the last field.

This is not true, it works as expected. You removed entirely a referenced entity which got removed from the system so it was no longer available as the "existing translation" to compare to.

2023-03-20 16:04 UTC, upchuk commented on modules/oe_translation_local/tests/src/Functional/LocalTranslationsTest.php
> +    $this->assertSession()->pageTextNotContains('top field value 1 FR');
Would be good to have an assertion that this is shown before we clear them in the translation sync process.

2023-03-21 07:13 UTC, upchuk commented on modules/oe_translation_local/tests/src/Functional/LocalTranslationsTest.php
> +   * Tests that translations can be synced when the original node is updated.
Tests that translation values are removed upon sync when source ones are removed

2023-03-21 07:13 UTC, upchuk commented on modules/oe_translation_local/tests/src/Functional/LocalTranslationsTest.php
> +    $role->revokePermission('edit any oe_demo_translatable_page content');
Why revoke?

2023-03-22 16:51 UTC, hernani approved these changes, later dismissed

2023-03-22 17:30 UTC, 22Alexandra approved these changes

2023-03-22 17:52 UTC, merged