EWPP-3205: Various UX improvements.
openeuropa/oe_translation pull request #233
Opened 2023-04-03 12:44 UTC by upchuk

2023-04-03 14:23 UTC, 22Alexandra requested changes

2023-04-03 14:23 UTC, 22Alexandra commented on modules/oe_translation_corporate_workflow/tests/src/Functional/CorporateWorkflowTranslationTest.php
> +    // Assert the dashboard contains to ongoing requests.
```suggestion
    // Assert the dashboard contains the ongoing request.
```

2023-04-03 14:23 UTC, 22Alexandra commented on modules/oe_translation_epoetry/oe_translation_epoetry.module
> +  // continued anymore so the request needs be finished.
```suggestion
  // continued anymore so the request needs to be finished.
```

2023-04-03 14:23 UTC, 22Alexandra commented on modules/oe_translation_epoetry/oe_translation_epoetry.module
> +    if ($language_with_status->getStatus() !== TranslationRequestEpoetryInterface::STATUS_LANGUAGE_CANCELLED) {
We should mark the request as finished if all the requested languages are either cancelled, accepted or synchronised (basically sent from ePoetry), not just cancelled.

2023-04-03 15:14 UTC, upchuk commented on modules/oe_translation_epoetry/oe_translation_epoetry.module
> +    if ($language_with_status->getStatus() !== TranslationRequestEpoetryInterface::STATUS_LANGUAGE_CANCELLED) {
No, if a language is accepted locally, it means the request should stil be open, as the user still needs to sync it

2023-04-03 15:25 UTC, upchuk commented on modules/oe_translation_epoetry/oe_translation_epoetry.module
> +    if ($language_with_status->getStatus() !== TranslationRequestEpoetryInterface::STATUS_LANGUAGE_CANCELLED) {
Fixed to take into account the synced languages

2023-04-03 15:49 UTC, 22Alexandra approved these changes

2023-04-04 10:33 UTC, hernani approved these changes

2023-04-04 10:34 UTC, merged