EWPP-3205: Adding Rejected product status.
openeuropa/oe_translation pull request #234
Opened 2023-04-06 12:54 UTC by upchuk

2023-04-10 09:22 UTC, 22Alexandra requested changes
I found this issue (might be related to the mock only):

I have an ongoing request where the 1st language is Rejected, the 2nd one is Cancelled and after the 3rd language is Translated the request status is updated to Translated but the `newTranslationRequestForm` is called. Shouldn't it be called only after the request is marked as Finished?
![new request](https://user-images.githubusercontent.com/22908988/230872351-16b63f25-b239-4f65-9d42-e62884fd1344.png)
 
Then, I was able to add new languages (Hungarian) to this request:
![new language to Translated request](https://user-images.githubusercontent.com/22908988/230872668-cdc009ec-8818-4982-a8c2-e0d9dcf47b8b.png)

While I already have two ongoing requests I can start another one:
![new request while 2 are already ongoing](https://user-images.githubusercontent.com/22908988/230872941-fc82514e-16ca-4de3-9a79-fc30063b1db8.png)

2023-04-10 09:22 UTC, 22Alexandra commented on modules/oe_translation_epoetry/oe_translation_epoetry.module
> +  // cannot be continued anymore so the they should allow the request to be
Same below on line 357.
```suggestion
  // cannot be continued anymore so they should allow the request to be
```

2023-04-10 09:22 UTC, 22Alexandra commented on modules/oe_translation_epoetry/src/RequestFactory.php
> +    if ($comment !== "") {
Use single quotes.

2023-04-10 09:42 UTC, upchuk commented
@22Alexandra RE the comment with the screenshot, yes, it's a bit weird, but there are 2 things:

1. When the request is Translated on our side, we need to still allow to add new languages. As per DGT request
2. Yes, a bit weird that if all languages arrive (or some of them get rejected/cancelled), we can the make an entirely new request as well (before updating the content). But that has been like that frm the beginning and it's ok. The API allows us to do that and can unblock certain use cases in which there is a mistake (for example, they rejected or cancelled a translation by mistake). Typically, translators wont do this because they won't have the need to do.

2023-04-11 12:56 UTC, hernani commented on modules/oe_translation_corporate_workflow/tests/src/Functional/CorporateWorkflowTranslationTest.php
> +   * translation. We ensure that when we sync onto that Published version which
Published version, which

2023-04-11 12:56 UTC, hernani commented on modules/oe_translation_corporate_workflow/tests/src/Functional/CorporateWorkflowTranslationTest.php
> +   * The tested use case is having a translation started from a Published
The test starts with a translation started from a Published version that becomes unpublished, followed by syncing that ongoing translation.

2023-04-11 13:02 UTC, 22Alexandra approved these changes

2023-04-11 13:05 UTC, hernani approved these changes

2023-04-11 13:22 UTC, merged