EWPP-3285: Ensuring that block field reference value is not translatable
openeuropa/oe_translation pull request #267
Opened 2023-06-27 08:24 UTC by upchuk

2023-06-27 14:22 UTC, 22Alexandra commented on modules/oe_translation_block_field/src/BlockFieldProcessor.php
> +    // The block field is usually marked as translatable so that it's title
```suggestion
    // The block field is usually marked as translatable so that its title
```

2023-06-27 14:22 UTC, 22Alexandra submitted a review, later dismissed

2023-06-28 11:24 UTC, nagyad requested changes

2023-06-28 11:24 UTC, nagyad commented on modules/oe_translation_block_field/tests/src/Kernel/BlockFieldTest.php
> +    $this->assertEquals($settings['label'], 'Hello DE');
First parameter should be expected and second the actual. I assume here 'Hello DE' is the expected.

2023-06-28 11:24 UTC, nagyad commented on modules/oe_translation_block_field/tests/src/Kernel/BlockFieldTest.php
> +    $this->assertEquals($data['field_block_field'][0]['settings__label']['#text'], 'Hello - updated');
First parameter should be expected and second the actual.

2023-06-28 11:24 UTC, nagyad commented on modules/oe_translation_block_field/tests/src/Kernel/BlockFieldTest.php
> +    $this->assertEquals($settings['label'], 'Hello - updated DE');
First parameter should be expected and second the actual.

2023-06-28 11:36 UTC, 22Alexandra approved these changes

2023-06-28 11:40 UTC, nagyad approved these changes

2023-07-26 06:18 UTC, merged