D8AGE-286: Init CDT submodule.
openeuropa/oe_translation pull request #297
Opened 2024-03-14 08:42 UTC by intelektron

## D8AGE-286

### Description

New submodule for CDT, with config requirements.

### Change log

- Added: The submodule, config requirements, test for requirements

2024-03-14 11:22 UTC, intelektron commented on modules/oe_translation_cdt/tests/src/Kernel/RequirementsTest.php
> +            'severity' => 0,
Using constant here throws an type error, it seems like some PHPUnit issue.

2024-03-14 11:23 UTC, intelektron commented on modules/oe_translation_cdt/tests/src/Kernel/RequirementsTest.php
> +  public static function cdtRequirementsProvider(): array {
I saw Francesco's comment about avoiding providers after creating this PR, I can change this test to eliminate the provider, if needed.

2024-03-25 10:12 UTC, drishu requested changes
Lets improve the PR title, something like Scaffold CDT submodule or Add ... or Create...

2024-03-25 10:12 UTC, drishu commented on .drone.yml
> +      - CDT_TOKEN_API_ENDPOINT=https://example.com/token
not sure when these example.com values will come into play, can we remove them and add anything only when needed

2024-03-25 10:12 UTC, drishu commented on modules/oe_translation_cdt/oe_translation_cdt.install
> +
remove this newline, the if statement already demarcates the code block

2024-03-25 10:12 UTC, drishu commented on modules/oe_translation_cdt/tests/src/Kernel/RequirementsTest.php
> +      $this->assertEquals(0, $requirements[$name]['severity']);
can we use the REQUIREMENT_OK constant so its cleared

2024-03-25 10:12 UTC, drishu commented on modules/oe_translation_cdt/tests/src/Kernel/RequirementsTest.php
> +      $this->assertEquals(1, $requirements[$name]['severity']);
REQUIREMENT_WARNING

2024-03-25 11:39 UTC, drishu approved these changes

2024-03-26 12:39 UTC, imanoleguskiza approved these changes

2024-03-27 12:35 UTC, merged