EWPP-4233: EntityRevisionInfoSubscriber fixes.
openeuropa/oe_translation pull request #307
Opened 2024-04-25 12:30 UTC by upchuk

2024-05-13 14:54 UTC, nagyad requested changes

2024-05-13 14:54 UTC, nagyad commented on modules/oe_translation_corporate_workflow/src/EventSubscriber/EntityRevisionInfoSubscriber.php
> +    if (!$workflow || $workflow->id() !== 'oe_corporate_workflow' || !\Drupal::service('oe_translation.translator_providers')->hasTranslators($entity->getEntityType())) {
Dependency injection.

2024-05-22 08:46 UTC, nagyad approved these changes, later dismissed

2024-05-23 07:06 UTC, 22Alexandra approved these changes

2024-06-07 13:52 UTC, merged