EWPP-4241: Allowing for remote translations to work without local ones.
openeuropa/oe_translation pull request #308
Opened 2024-05-12 16:20 UTC by upchuk

In this PR we allow the situation in which for an entity type, we use the remote translations but we don't also use the local translation. Instead, for local, the regular Drupal core system stays. However, there is still the override of not creating a new revision upon translation saving even for regular Drupal core translations.

2024-05-24 07:10 UTC, 22Alexandra approved these changes

2024-05-24 10:00 UTC, 22Alexandra approved these changes

2024-05-31 08:45 UTC, 22Alexandra approved these changes

2024-05-31 17:13 UTC, nagyad requested changes

2024-05-31 17:13 UTC, nagyad commented on modules/oe_translation_corporate_workflow/tests/modules/oe_translation_corporate_workflow_test/oe_translation_corporate_workflow_test.module
> +      $entity_type->set('oe_translation_translators', $translators);
We should break the cycle after this.

2024-05-31 17:13 UTC, nagyad commented on modules/oe_translation_corporate_workflow/src/Form/RevisionTranslationDeleteForm.php
> + * of that revision gets cleared without making any other change to the node
...any other change to the entity

2024-05-31 17:13 UTC, nagyad commented on modules/oe_translation_corporate_workflow/tests/src/Functional/CorporateWorkflowTranslationTest.php
> +   * Test that we don't get a validation error by the  EntityChangedConstraint.
Double space.

2024-05-31 17:13 UTC, nagyad commented on tests/modules/oe_translation_menu_link_test/oe_translation_menu_link_test.module
> +      $entity_type->set('oe_translation_translators', $translators);
We can stop the cycle here.

2024-06-07 14:32 UTC, merged